language: c

cache:
  directories:
    - $HOME/travis-cache

os:
  - osx

osx_image: xcode10.1

compiler:
  - gcc

before_install: ci/install-dependencies.sh
script: ci/run-build-and-tests.sh
after_failure: ci/print-test-failures.sh

notifications:
  email: false
